name: ci

on:
  push:
    branches:
      - '**'

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set base dir
        run: |
          echo "NAT_BASE_DIR=${{ github.workspace }}/" >> $GITHUB_ENV
      - name: Build
        run: make nat
      - name: Run integration tests
        run: make integration
      - name: Run regression tests
        run: make regression
      - name: Run trip tests
        run: make trip
      - name: Run integration tests against valgrind
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update && sudo apt install -y valgrind
          make test-valgrind
      - name: Run integration tests against leaks
        if: matrix.os == 'macos-latest'
        run: make test-leaks
      - name: Stress the garbage collector
        run: |
          sudo make clean
          make debug-stress-gc
          make tests
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/setup-node@v4
      - name: Set base dir
        run: |
          echo "NAT_BASE_DIR=${{ github.workspace }}/" >> $GITHUB_ENV
      - name: Test wasm
        run: NAT_BASE_DIR="./" emmake make test-wasm