name: release

on:
  push:
    branches:
      - main

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to ECR
        run: docker login -u AWS -p $(aws ecr get-login-password --region us-east-2) ${{ secrets.ECR_REPOSITORY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ secrets.ECR_REPOSITORY }}/nat:latest
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v14
      - name: Build wasm
        run: NAT_BASE_DIR="./" emmake make wasm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build & release npm
        working-directory: "wasm"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i
          npm run build
          npm publish --access public
